apiVersion: v1
kind: Service
metadata:
  name: gold-price-service
spec:
  type: NodePort
  selector:
    app: gold-price-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
  nodePort: 30007